### PR TITLE
Add CMake components to neatly install individual libraries

### PR DESCRIPTION
**Pull request by delta512**
Dear maintainers,
as you might guess from the title, I've just specified the `COMPONENT` attribute for each `install()` directive.
These are `qrcodegen` for the C library and `qrcodegencpp` for the C++ implementation.

This enables installing only one of the two library flavors with commands in the form:
`cmake --install <build_dir> [--prefix <install_dir>] --component <component>`

My use case for this is to produce split packages in a more elegant way. As an example, split packages for Arch Linux can be created with both libraries sharing a common build and test process, then they can be packaged separately without all those clean-up instructions (as seen in the [qrcodegen-cmake](https://aur.archlinux.org/qrcodegen-cmake.git) AUR package).

Thanks for your time, hope you'll find it useful as well.

Cheers!

### CODE REVIEW

**Review by xvitaly — COMMENTED** [review]
Please squash your commits to a single one and add a sign-off (you can use `git commit -s` and the Git will handle it automatically).

We need signed-off commits for sending changes to the upstream.

**Comment by delta512** [comment]
Hi all, glad you appreciated it.

> Please squash your commits to a single one and add a sign-off (you can use `git commit -s` and the Git will handle it automatically).
> 
> We need signed-off commits for sending changes to the upstream.

To @xvitaly, I've squashed the fix into the main commit and signed-off as requested, please just check if anything else is missing.

> Big thanks for your PR! Looks great for me One negligible comment: may you update the README for users how to install both libraries with CMake components (like "`sudo cmake --install qrcodegen-build --component qrcodegencpp`")

To @leha-bot, I've added the instructions concerning the CMake components, let me know if it blends well into the rest.

Thanks to both,
Cheers!

**Review by xvitaly — APPROVED** [review]
LGTM now. Thanks for your contribution.

**Comment by delta512** [comment]
My pleasure!

Thank you all for reacting so quickly, I can keep pulling from upstream in my PKGBUILD. 😎

Hasta la vista!

**Pull request merged**
